name: Notify forked repositories on push

on:
  push:
    branches:
      - main

jobs:
  notify_forks:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync for forked repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/last-brain-cell/stepnex-website-latest/dispatches \
            -d '{"event_type": "sync_upstream"}'
