name: Sync with upstream
on:
  repository_dispatch:
    types: [sync_upstream]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set git config
        run: |
          git config --global user.name 'last-brain-cell'
          git config --global user.email 'naadkd@gmail.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/StepnexTechnologies/Company-Website.git || echo "Upstream remote already exists"

      - name: Sync with upstream main branch
        run: |
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main || echo "Merge conflict in main. Skipping."

      - name: Trigger Vercel Deployment via API
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_FqpdCYSvg1Y82i5hLjF5bcu5Kf5W" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -d '{"name": "Your Project Name", "gitSource": {"ref": "main"}}'
